// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../lib/app/showcase-debug.js', ['app.Showdebug'], ['goog.debug.FancyWindow', 'goog.debug.LogManager', 'goog.debug.Logger']);
goog.addDependency('../../../lib/app/ui-events.js', ['app.ui.Debug'], ['app.Module', 'app.Showdebug', 'ssd.debug']);
goog.addDependency('../../../lib/core/core.js', ['app.Core', 'appOne'], ['app.Module', 'app.ui.Debug', 'ssd.helpers', 'ssd.invocator']);
goog.addDependency('../../../lib/core/exports.js', ['app.exports'], ['app.Core', 'app.ajax', 'app.sync', 'appOne']);
goog.addDependency('../../../lib/core/response.core.js', ['app.Response'], ['goog.events.Event', 'goog.object']);
goog.addDependency('../../../lib/helpers/debug.js', ['ssd.debug'], ['goog.debug', 'goog.debug.FancyWindow', 'goog.debug.LogManager', 'goog.debug.Logger']);
goog.addDependency('../../../lib/helpers/helpers.js', ['ssd.helpers'], ['goog.array', 'goog.json', 'goog.object']);
goog.addDependency('../../../lib/libs/invocator.js', ['ssd.invocator'], ['goog.object']);
goog.addDependency('../../../lib/libs/module.js', ['app.Module'], ['goog.events.EventTarget']);
goog.addDependency('../../../lib/libs/vendor.loader.js', ['ssd.vendor'], []);
goog.addDependency('../../../lib/main.js', ['app'], ['app.Core', 'app.exports', 'ssd.debug', 'ssd.vendor']);
goog.addDependency('../../../lib/network/ajax.js', ['app.ajax', 'app.ajax.Method'], ['app.sync.Response', 'goog.Uri', 'goog.net.XhrIo', 'ssd.helpers']);
goog.addDependency('../../../lib/network/response.sync.js', ['app.sync.Response', 'app.sync.T'], ['app.Response', 'goog.object']);
goog.addDependency('../../../lib/network/sync.js', ['app.sync'], ['app.ajax', 'app.sync.Response']);
