// This file was autogenerated by app/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/app/showcase-debug.js', ['app.Showdebug'], ['goog.debug.FancyWindow', 'goog.debug.LogManager', 'goog.debug.Logger']);
goog.addDependency('../../../js/app/ui-events.js', ['app.ui.Debug'], ['app.Module', 'app.Showdebug', 'ssd.debug']);
goog.addDependency('../../../js/core/core.js', ['app', 'app.Core', 'theApp'], ['app.Module', 'app.ui.Debug', 'ssd.helpers', 'ssd.invocator']);
goog.addDependency('../../../js/core/exports.js', ['app.exports'], ['app.Core', 'app.ajax', 'app.sync', 'theApp']);
goog.addDependency('../../../js/core/response.core.js', ['app.Response'], ['goog.events.Event', 'goog.object']);
goog.addDependency('../../../js/helpers/debug.js', ['ssd.debug'], ['goog.debug', 'goog.debug.FancyWindow', 'goog.debug.LogManager', 'goog.debug.Logger']);
goog.addDependency('../../../js/helpers/helpers.js', ['ssd.helpers'], ['goog.array', 'goog.json', 'goog.object']);
goog.addDependency('../../../js/libs/invocator.js', ['ssd.invocator'], ['goog.object']);
goog.addDependency('../../../js/libs/module.js', ['app.Module'], ['goog.events.EventTarget']);
goog.addDependency('../../../js/main.js', ['___bootstrap___'], ['app.Core', 'app.exports', 'ssd.debug', 'ssd.vendor']);
goog.addDependency('../../../js/network/ajax.js', ['app.ajax', 'app.ajax.Method'], ['app.sync.Response', 'goog.Uri', 'goog.net.XhrIo']);
goog.addDependency('../../../js/network/response.sync.js', ['app.sync.Response', 'app.sync.T'], ['app.Response', 'goog.object']);
goog.addDependency('../../../js/network/sync.js', ['app.sync'], ['app.ajax', 'app.sync.Response']);
goog.addDependency('../../../js/vendor/vendor.main.js', ['ssd.vendor'], []);
