(function(){var h=!0,k=null,l=!1,m=this;
function aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function n(a){return a[q]||(a[q]=++ba)}var q="closure_uid_"+(1E9*Math.random()>>>0),ba=0;function ca(a,b,c){return a.call.apply(a.bind,arguments)}function da(a,b,c){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}
function r(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return r.apply(k,arguments)}function s(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c};var t="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ea(a,b){for(var c,e,f=1;f<arguments.length;f++){e=arguments[f];for(c in e)a[c]=e[c];for(var d=0;d<t.length;d++)c=t[d],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};var u=Array.prototype,fa=u.indexOf?function(a,b,c){return u.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:0>c?Math.max(0,a.length+c):c;if("string"==typeof a)return"string"!=typeof b||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function ga(){};var v,w,y,z;function A(){return m.navigator?m.navigator.userAgent:k}z=y=w=v=l;var B;if(B=A()){var ia=m.navigator;v=0==B.indexOf("Opera");w=!v&&-1!=B.indexOf("MSIE");y=!v&&-1!=B.indexOf("WebKit");z=!v&&!y&&"Gecko"==ia.product}var C=v,D=w,E=z,F=y;function G(){var a=m.document;return a?a.documentMode:void 0}var H;
a:{var I="",J;if(C&&m.opera)var K=m.opera.version,I="function"==typeof K?K():K;else if(E?J=/rv\:([^\);]+)(\)|;)/:D?J=/MSIE\s+([^\);]+)(\)|;)/:F&&(J=/WebKit\/(\S+)/),J)var L=J.exec(A()),I=L?L[1]:"";if(D){var N=G();if(N>parseFloat(I)){H=String(N);break a}}H=I}var ja={};
function O(a){var b;if(!(b=ja[a])){b=0;for(var c=String(H).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,e.length),d=0;0==b&&d<f;d++){var g=c[d]||"",p=e[d]||"",M=RegExp("(\\d*)(\\D*)","g"),x=RegExp("(\\d*)(\\D*)","g");do{var i=M.exec(g)||["","",""],j=x.exec(p)||["","",""];if(0==i[0].length&&0==j[0].length)break;b=((0==i[1].length?0:parseInt(i[1],10))<(0==j[1].length?0:parseInt(j[1],10))?-1:(0==i[1].length?0:parseInt(i[1],
10))>(0==j[1].length?0:parseInt(j[1],10))?1:0)||((0==i[2].length)<(0==j[2].length)?-1:(0==i[2].length)>(0==j[2].length)?1:0)||(i[2]<j[2]?-1:i[2]>j[2]?1:0)}while(0==b)}b=ja[a]=0<=b}return b}var ka=m.document,la=!ka||!D?void 0:G()||("CSS1Compat"==ka.compatMode?parseInt(H,10):5);if(E||D){var P;if(P=D)P=D&&9<=la;P||E&&O("1.9.1")}D&&O("9");function ma(){0!=na&&(this.s=Error().stack,n(this))}var na=0;D&&O("9");!F||O("528");E&&O("1.9b")||D&&O("8")||C&&O("9.5")||F&&O("528");E&&!O("8")||D&&O("9");function Q(a,b){this.type=a;this.currentTarget=this.target=b}Q.prototype.f=l;Q.prototype.defaultPrevented=l;Q.prototype.d=h;Q.prototype.preventDefault=function(){this.defaultPrevented=h;this.d=l};var oa={},S={},T={},U={};function pa(a,b,c,e,f){if("array"==aa(b))for(var d=0;d<b.length;d++)pa(a,b[d],c,e,f);else{e=!!e;a:{d=S;if(b in d&&(d=d[b],e in d&&(d=d[e],a=n(a),d[a]))){a=d[a];break a}a=k}if(a)for(d=0;d<a.length;d++)if(a[d].v==c&&a[d].capture==e&&a[d].u==f){qa(a[d].key);break}}}
function qa(a){var b=oa[a];if(b&&!b.g){var c=b.src,e=b.type,f=b.proxy,d=b.capture;c.removeEventListener?(c==m||!c.customEvent_)&&c.removeEventListener(e,f,d):c.detachEvent&&c.detachEvent(e in U?U[e]:U[e]="on"+e,f);c=n(c);if(T[c]){var f=T[c],g=fa(f,b);0<=g&&u.splice.call(f,g,1);0==f.length&&delete T[c]}b.g=h;if(b=S[e][d][c])b.l=h,ra(e,d,c,b);delete oa[a]}}
function ra(a,b,c,e){if(!e.c&&e.l){for(var f=0,d=0;f<e.length;f++)e[f].g?e[f].proxy.src=k:(f!=d&&(e[d]=e[f]),d++);e.length=d;e.l=l;0==d&&(delete S[a][b][c],S[a][b].b--,0==S[a][b].b&&(delete S[a][b],S[a].b--),0==S[a].b&&delete S[a])}}
function V(a,b,c,e,f){var d=1;b=n(b);if(a[b]){var g=--a.a,p=a[b];p.c?p.c++:p.c=1;try{for(var M=p.length,x=0;x<M;x++){var i=p[x];if(i&&!i.g){var j=d,ha,R=i,sa=f;R.r&&qa(R.key);ha=R.handleEvent(sa);d=j&ha!==l}}}finally{a.a=Math.max(g,a.a),p.c--,ra(c,e,b,p)}}return Boolean(d)};function W(){ma.call(this);this.t={};this.q=this}s(W,ma);W.prototype.customEvent_=h;W.prototype.m=k;W.prototype.removeEventListener=function(a,b,c,e){pa(this,a,b,c,e)};
W.prototype.dispatchEvent=function(a){var b=a.type||a,c=S;if(b in c){if("string"==typeof a)a=new Q(a,this);else if(a instanceof Q)a.target=a.target||this;else{var e=a;a=new Q(b,this);ea(a,e)}var e=1,f,c=c[b],b=h in c,d;if(b){f=[];for(d=this;d;d=d.m)f.push(d);d=c[h];d.a=d.b;for(var g=f.length-1;!a.f&&0<=g&&d.a;g--)a.currentTarget=f[g],e&=V(d,f[g],a.type,h,a)&&a.d!=l}if(l in c)if(d=c[l],d.a=d.b,b)for(g=0;!a.f&&g<f.length&&d.a;g++)a.currentTarget=f[g],e&=V(d,f[g],a.type,l,a)&&a.d!=l;else for(f=this;!a.f&&
f&&d.a;f=f.m)a.currentTarget=f,e&=V(d,f,a.type,l,a)&&a.d!=l;a=Boolean(e)}else a=h;return a};function X(){W.call(this)}s(X,W);function Y(){W.call(this);this.i=this.h=this.j=k}s(Y,X);Y.prototype.e=function(){this.j=$("#output");this.h=$("#showdebug");this.i=$("#openFancyWindow");this.h.on("click",r(this.n,this));this.i.on("click",r(this.o))};Y.prototype.n=function(a){a.preventDefault();this.j.append("Clicked Log<br>")};Y.prototype.o=function(a){a.preventDefault()};function Z(){W.call(this);this.k=l;this.p=new Y}s(Z,X);Z.prototype.e=function(a){a=a||ga;this.k?a():(this.p.e(),this.k=h,this.dispatchEvent("init"))};Z.prototype.toString=function(){return"awesome app"};(new Z).e();}).call(this);
