(function(){var h=void 0,i=!0,j=null,k=!1,n,q=this;function aa(a){for(var a=a.split("."),b=q,c;c=a.shift();)if(b[c]!=j)b=b[c];else return j;return b}
function r(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ba(a){var b=r(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"string"==typeof a}function ca(a){var b=typeof a;return"object"==b&&a!=j||"function"==b}var v="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function w(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return w.apply(j,arguments)}var x=Date.now||function(){return+new Date};
function ga(a,b){function c(){}c.prototype=b.prototype;a.I=b.prototype;a.prototype=new c};function ha(a,b){return a.replace(/(\r\n|\r|\n)/g,b?"<br />":"<br>")}function y(a){if(!ia.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ja,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ka,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(la,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ma,"&quot;"));return a}var ja=/&/g,ka=/</g,la=/>/g,ma=/\"/g,ia=/[&<>\"]/;function na(a){return ha(a.replace(/  /g," &#160;"),h)};var z,oa,pa,qa;function ra(){return q.navigator?q.navigator.userAgent:j}qa=pa=oa=z=k;var sa;if(sa=ra()){var ta=q.navigator;z=0==sa.indexOf("Opera");oa=!z&&-1!=sa.indexOf("MSIE");pa=!z&&-1!=sa.indexOf("WebKit");qa=!z&&!pa&&"Gecko"==ta.product}var ua=z,A=oa,B=qa,C=pa,va;
a:{var wa="",D;if(ua&&q.opera)var xa=q.opera.version,wa="function"==typeof xa?xa():xa;else if(B?D=/rv\:([^\);]+)(\)|;)/:A?D=/MSIE\s+([^\);]+)(\)|;)/:C&&(D=/WebKit\/(\S+)/),D)var ya=D.exec(ra()),wa=ya?ya[1]:"";if(A){var za,Aa=q.document;za=Aa?Aa.documentMode:h;if(za>parseFloat(wa)){va=""+za;break a}}va=wa}var Ba={};
function E(a){var b;if(!(b=Ba[a])){b=0;for(var c=(""+va).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=(""+a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",l=d[e]||"",o=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var s=o.exec(g)||["","",""],p=m.exec(l)||["","",""];if(0==s[0].length&&0==p[0].length)break;b=((0==s[1].length?0:parseInt(s[1],10))<(0==p[1].length?0:parseInt(p[1],10))?-1:(0==s[1].length?0:parseInt(s[1],
10))>(0==p[1].length?0:parseInt(p[1],10))?1:0)||((0==s[2].length)<(0==p[2].length)?-1:(0==s[2].length)>(0==p[2].length)?1:0)||(s[2]<p[2]?-1:s[2]>p[2]?1:0)}while(0==b)}b=Ba[a]=0<=b}return b}var Ca={};function Da(){return Ca[9]||(Ca[9]=A&&!!document.documentMode&&9<=document.documentMode)};function Ea(){}var Fa=0;n=Ea.prototype;n.key=0;n.k=k;n.N=k;n.i=function(a,b,c,d,f,e){if("function"==r(a))this.R=i;else if(a&&a.handleEvent&&"function"==r(a.handleEvent))this.R=k;else throw Error("Invalid listener argument");this.u=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!f;this.P=e;this.N=k;this.key=++Fa;this.k=k};n.handleEvent=function(a){return this.R?this.u.call(this.P||this.src,a):this.u.handleEvent.call(this.u,a)};function Ga(a,b){for(var c in a)b.call(h,a[c],c,a)}var Ha="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ia(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Ha.length;e++)c=Ha[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};!A||Da();var Ja=!A||Da(),Ka=A&&!E("8");!C||E("528");B&&E("1.9b")||A&&E("8")||ua&&E("9.5")||C&&E("528");B&&!E("8")||A&&E("9");var F=Array.prototype,La=F.indexOf?function(a,b,c){return F.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:0>c?Math.max(0,a.length+c):c;if(u(a))return!u(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ma=F.forEach?function(a,b,c){F.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=u(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};function Na(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function Oa(a,b,c){return 2>=arguments.length?F.slice.call(a,b):F.slice.call(a,b,c)};function Pa(){}Pa.prototype.O=k;Pa.prototype.q=function(){this.O||(this.O=i,this.r())};Pa.prototype.r=function(){this.ea&&Qa.apply(j,this.ea);if(this.V)for(;this.V.length;)this.V.shift()()};function Qa(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ba(d)?Qa.apply(j,d):d&&"function"==typeof d.q&&d.q()}};function G(a,b){this.type=a;this.currentTarget=this.target=b}ga(G,Pa);G.prototype.r=function(){delete this.type;delete this.target;delete this.currentTarget};G.prototype.H=k;G.prototype.defaultPrevented=k;G.prototype.preventDefault=function(){this.defaultPrevented=i};function Ra(a){Ra[" "](a);return a}Ra[" "]=function(){};function H(a,b){a&&this.i(a,b)}ga(H,G);n=H.prototype;n.target=j;n.relatedTarget=j;n.offsetX=0;n.offsetY=0;n.clientX=0;n.clientY=0;n.screenX=0;n.screenY=0;n.button=0;n.keyCode=0;n.charCode=0;n.ctrlKey=k;n.altKey=k;n.shiftKey=k;n.metaKey=k;n.A=j;
n.i=function(a,b){var c=this.type=a.type;G.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(B){var f;a:{try{Ra(d.nodeName);f=i;break a}catch(e){}f=k}f||(d=j)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=C||a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=C||a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.A=a;a.defaultPrevented&&this.preventDefault();delete this.H};
n.preventDefault=function(){H.I.preventDefault.call(this);var a=this.A;if(a.preventDefault)a.preventDefault();else if(a.returnValue=k,Ka)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};n.r=function(){H.I.r.call(this);this.relatedTarget=this.currentTarget=this.target=this.A=j};var I={},J={},K={},L={};
function Sa(a,b,c,d,f){if(b)if("array"==r(b))for(var e=0;e<b.length;e++)Sa(a,b[e],c,d,f);else{var d=!!d,g=J;b in g||(g[b]={e:0,g:0});g=g[b];d in g||(g[d]={e:0,g:0},g.e++);var g=g[d],l=a[v]||(a[v]=++da),o;g.g++;if(g[l]){o=g[l];for(e=0;e<o.length;e++)if(g=o[e],g.u==c&&g.P==f){if(g.k)break;return}}else o=g[l]=[],g.e++;e=Ta();e.src=a;g=new Ea;g.i(c,e,a,b,d,f);c=g.key;e.key=c;o.push(g);I[c]=g;K[l]||(K[l]=[]);K[l].push(g);a.addEventListener?(a==q||!a.da)&&a.addEventListener(b,e,d):a.attachEvent(b in L?
L[b]:L[b]="on"+b,e)}else throw Error("Invalid event type");}function Ta(){var a=Ua,b=Ja?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}function Va(a,b,c,d){if(!d.v&&d.U){for(var f=0,e=0;f<d.length;f++)d[f].k?d[f].proxy.src=j:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.U=k;0==e&&(delete J[a][b][c],J[a][b].e--,0==J[a][b].e&&(delete J[a][b],J[a].e--),0==J[a].e&&delete J[a])}}
function Wa(a,b,c,d,f){var e=1,b=b[v]||(b[v]=++da);if(a[b]){a.g--;a=a[b];a.v?a.v++:a.v=1;try{for(var g=a.length,l=0;l<g;l++){var o=a[l];o&&!o.k&&(e&=Xa(o,f)!==k)}}finally{a.v--,Va(c,d,b,a)}}return Boolean(e)}
function Xa(a,b){if(a.N){var c=a.key;if(I[c]){var d=I[c];if(!d.k){var f=d.src,e=d.type,g=d.proxy,l=d.capture;f.removeEventListener?(f==q||!f.da)&&f.removeEventListener(e,g,l):f.detachEvent&&f.detachEvent(e in L?L[e]:L[e]="on"+e,g);f=f[v]||(f[v]=++da);g=J[e][l][f];if(K[f]){var o=K[f],m=La(o,d);0<=m&&F.splice.call(o,m,1);0==o.length&&delete K[f]}d.k=i;g.U=i;Va(e,l,f,g);delete I[c]}}}return a.handleEvent(b)}
function Ua(a,b){if(!I[a])return i;var c=I[a],d=c.type,f=J;if(!(d in f))return i;var f=f[d],e,g;if(!Ja){e=b||aa("window.event");var l=i in f,o=k in f;if(l){if(0>e.keyCode||e.returnValue!=h)return i;a:{var m=k;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(s){m=i}if(m||e.returnValue==h)e.returnValue=i}}m=new H;m.i(e,this);e=i;try{if(l){for(var p=[],U=m.currentTarget;U;U=U.parentNode)p.push(U);g=f[i];g.g=g.e;for(var t=p.length-1;!m.H&&0<=t&&g.g;t--)m.currentTarget=p[t],e&=Wa(g,p[t],d,i,m);if(o){g=f[k];
g.g=g.e;for(t=0;!m.H&&t<p.length&&g.g;t++)m.currentTarget=p[t],e&=Wa(g,p[t],d,k,m)}}else e=Xa(c,m)}finally{p&&(p.length=0),m.q()}return e}d=new H(b,this);try{e=Xa(c,d)}finally{d.q()}return e};function Ya(){this.W=x()}var Za=new Ya;Ya.prototype.set=function(a){this.W=a};Ya.prototype.reset=function(){this.set(x())};Ya.prototype.get=function(){return this.W};function M(a){this.G=a||"";this.sa=Za}M.prototype.oa=i;M.prototype.qa=i;M.prototype.pa=i;M.prototype.Y=k;function N(a){return 10>a?"0"+a:""+a}function $a(a,b){var c=(a.Z-b)/1E3,d=c.toFixed(3),f=0;if(1>c)f=2;else for(;100>c;)f++,c*=10;for(;0<f--;)d=" "+d;return d}function ab(a){M.call(this,a)}ga(ab,M);ab.prototype.Y=i;function bb(a){this.F=a||100;this.d=[]}n=bb.prototype;n.n=0;n.add=function(a){this.d[this.n]=a;this.n=(this.n+1)%this.F};n.get=function(a){a=cb(this,a);return this.d[a]};n.set=function(a,b){a=cb(this,a);this.d[a]=b};n.clear=function(){this.n=this.d.length=0};function cb(a,b){if(b>=a.d.length)throw Error("Out of bounds exception");return a.d.length<a.F?b:(a.n+Number(b))%a.F};function db(a){return eb(a||arguments.callee.caller,[])}
function eb(a,b){var c=[];if(0<=La(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(fb(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){0<f&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=""+e;break;case "boolean":e=e?"true":"false";break;case "function":e=(e=fb(e))?e:"[fn]";break;default:e=typeof e}40<e.length&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(eb(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function fb(a){if(O[a])return O[a];a=""+a;if(!O[a]){var b=/function ([^\(]+)/.exec(a);O[a]=b?b[1]:"[Anonymous]"}return O[a]}var O={};function P(a,b,c,d,f){this.reset(a,b,c,d,f)}P.prototype.C=j;P.prototype.B=j;var gb=0;P.prototype.reset=function(a,b,c,d,f){"number"==typeof f||gb++;this.Z=d||x();this.c=a;this.T=b;this.S=c;delete this.C;delete this.B};P.prototype.p=function(a){this.c=a};function Q(a){this.ka=a}Q.prototype.w=j;Q.prototype.c=j;Q.prototype.z=j;Q.prototype.m=j;function R(a,b){this.name=a;this.value=b}R.prototype.toString=function(){return this.name};var hb=new R("SHOUT",1200),ib=new R("SEVERE",1E3),jb=new R("WARNING",900),kb=new R("INFO",800),lb=new R("CONFIG",700),mb=[new R("OFF",Infinity),hb,ib,jb,kb,lb,new R("FINE",500),new R("FINER",400),new R("FINEST",300),new R("ALL",0)],S=j;
function nb(a){if(!S){S={};for(var b=0,c;c=mb[b];b++)S[c.value]=c,S[c.name]=c}return S[a]||j}n=Q.prototype;n.getParent=function(){return this.w};n.p=function(a){this.c=a};function ob(a){return a.c?a.c:a.w?ob(a.w):j}
n.log=function(a,b,c){if(a.value>=ob(this).value){a=this.ja(a,b,c);b="log:"+a.T;q.console&&(q.console.timeStamp?q.console.timeStamp(b):q.console.markTimeline&&q.console.markTimeline(b));q.msWriteProfilerMark&&q.msWriteProfilerMark(b);for(b=this;b;){var c=b,d=a;if(c.m)for(var f=0,e=h;e=c.m[f];f++)e(d);b=b.getParent()}}};
n.ja=function(a,b,c){var d=new P(a,""+b,this.ka);if(c){d.C=c;var f;var e=arguments.callee.caller;try{var g;var l=aa("window.location.href");if(u(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:l,stack:"Not available"};else{var o,m,s=k;try{o=c.lineNumber||c.ta||"Not available"}catch(p){o="Not available",s=i}try{m=c.fileName||c.filename||c.sourceURL||l}catch(U){m="Not available",s=i}g=s||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:o,fileName:m,
stack:c.stack||"Not available"}:c}f="Message: "+y(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+y(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+y(db(e)+"-> ")}catch(t){f="Exception trying to expose exception! You win, we lose. "+t}d.B=f}return d};n.info=function(a,b){this.log(kb,a,b)};var pb={},T=j;function qb(){T||(T=new Q(""),pb[""]=T,T.p(lb))}
function V(a){qb();var b;if(!(b=pb[a])){b=new Q(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=V(a.substr(0,c));c.z||(c.z={});c.z[d]=b;b.w=c;pb[a]=b}return b};function rb(a,b){this.f=a||"";this.G=b||"";this.j=[];this.o=new bb(sb);this.ma=w(this.aa,this);this.ia=new ab(this.G);this.ha={};if(i!=this.Q){this.Q=i;qb();var c=T,d=this.ma;c.m||(c.m=[]);c.m.push(d)}this.s="1"==tb(this.f,"enabled");q.setInterval(w(this.na,this),7500)}var sb=500;n=rb.prototype;n.$="LOGGING";n.fa=k;n.a=j;n.J=k;n.Q=k;n.M=j;n.D=x();n.i=function(){this.s&&ub(this)};function vb(a,b){a.s=b;a.s&&ub(a);wb(a,"enabled",b?"1":"0")}function W(a){return!!a.a&&!a.a.closed}
n.ba=function(){this.o.clear();W(this)&&this.L()};
n.aa=function(a){if(!this.ha[a.S]){var b=this.ia,c;switch(a.c.value){case hb.value:c="dbg-sh";break;case ib.value:c="dbg-sev";break;case jb.value:c="dbg-w";break;case kb.value:c="dbg-i";break;default:c="dbg-f"}var d=[];d.push(b.G," ");if(b.oa){var f=new Date(a.Z);d.push("[",N(f.getFullYear()-2E3)+N(f.getMonth()+1)+N(f.getDate())+" "+N(f.getHours())+":"+N(f.getMinutes())+":"+N(f.getSeconds())+"."+N(Math.floor(f.getMilliseconds()/10)),"] ")}b.qa&&d.push("[",na($a(a,b.sa.get())),"s] ");b.pa&&d.push("[",
y(a.S),"] ");d.push('<span class="',c,'">',ha(na(y(a.T))));b.Y&&a.C&&d.push("<br>",ha(na(a.B||"")));d.push("</span><br>");b=d.join("");this.s?(ub(this),this.o.add(b),xb(this,b)):this.o.add(b);this.fa&&a.c.value>=ib.value&&vb(this,i)}};function xb(a,b){a.j.push(b);q.clearTimeout(a.M);750<x()-a.D?a.K():a.M=q.setTimeout(w(a.K,a),250)}
n.K=function(){this.D=x();if(W(this)){var a=this.a.document.body,a=a&&100>=a.scrollHeight-(a.scrollTop+a.clientHeight);this.a.document.write(this.j.join(""));this.j.length=0;a&&this.a.scrollTo(0,1E6)}};function yb(a){for(var b=a.o,c=b.d.length,d=[],f=b.d.length-a.o.d.length;f<c;f++)d[f]=b.get(f);for(b=0;b<d.length;b++)xb(a,d[b])}
function ub(a){if(!W(a)&&!a.J){var b=tb(a.f,"dbg","0,0,800,500").split(","),c=Number(b[0]),d=Number(b[1]),f=Number(b[2]),b=Number(b[3]);a.J=i;a.a=window.open("",A?a.f.replace(/[\s\-\.\,]/g,"_"):a.f,"width="+f+",height="+b+",toolbar=no,resizable=yes,scrollbars=yes,left="+c+",top="+d+",status=no,screenx="+c+",screeny="+d);!a.a&&!a.ra&&(alert("Logger popup was blocked"),a.ra=i);a.J=k;a.a&&a.L()}}n.t=function(){return"*{font:normal 14px monospace;}.dbg-sev{color:#F00}.dbg-w{color:#E92}.dbg-sh{background-color:#fd4;font-weight:bold;color:#000}.dbg-i{color:#666}.dbg-f{color:#999}.dbg-ev{color:#0A0}.dbg-m{color:#990}"};
n.L=function(){W(this)||(this.a.document.open(),xb(this,"<style>"+this.t()+'</style><hr><div class="dbg-ev" style="text-align:center">'+this.$+"<br><small>Logger: "+this.f+"</small></div><hr>"),yb(this))};function wb(a,b,c){b+=a.f;document.cookie=b+"="+encodeURIComponent(c)+";path=/;expires="+(new Date(x()+2592E6)).toUTCString()}
function tb(a,b,c){var a=b+a,b=""+document.cookie,d=b.indexOf(a+"=");return-1!=d?(c=b.indexOf(";",d),decodeURIComponent(b.substring(d+a.length+1,-1==c?b.length:c))):c||""}n.na=function(){W(this)&&wb(this,"dbg",(this.a.screenX||this.a.screenLeft||0)+","+(this.a.screenY||this.a.screenTop||0)+","+(this.a.outerWidth||800)+","+(this.a.outerHeight||500))};function zb(a,b){var c;c=a.className;c=u(c)&&c.match(/\S+/g)||[];for(var d=Oa(arguments,1),f=c.length+d.length,e=c,g=0;g<d.length;g++)0<=La(e,d[g])||e.push(d[g]);a.className=c.join(" ");return c.length==f};var Ab=!A||Da();!B&&!A||A&&Da()||B&&E("1.9.1");A&&E("9");function Bb(a,b){Ga(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Cb?a.setAttribute(Cb[d],b):0==d.lastIndexOf("aria-",0)?a.setAttribute(d,b):a[d]=b})}var Cb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function Db(a,b,c){function d(c){c&&b.appendChild(u(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];if(ba(e)&&!(ca(e)&&0<e.nodeType)){var g;a:{if(e&&"number"==typeof e.length){if(ca(e)){g="function"==typeof e.item||"string"==typeof e.item;break a}if("function"==r(e)){g="function"==typeof e.item;break a}}g=k}Ma(g?Na(e):e,d)}else d(e)}}function X(a){this.l=a||q.document||document}function Y(a,b){return u(b)?a.l.getElementById(b):b}
X.prototype.h=function(a,b,c){var d=this.l,f=arguments,e=f[0],g=f[1];if(!Ab&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',y(g.name),'"');if(g.type){e.push(' type="',y(g.type),'"');var l={};Ia(l,g);g=l;delete g.type}e.push(">");e=e.join("")}e=d.createElement(e);g&&(u(g)?e.className=g:"array"==r(g)?zb.apply(j,[e].concat(g)):Bb(e,g));2<f.length&&Db(d,e,f);return e};X.prototype.createElement=function(a){return this.l.createElement(a)};X.prototype.createTextNode=function(a){return this.l.createTextNode(a)};
X.prototype.appendChild=function(a,b){a.appendChild(b)};function Eb(a,b){if(Fb){var c=Gb(),d;for(d in c){var f=d.replace("fancywindow.sel.",""),f=V(f),e=f.c,g=window.localStorage.getItem(d).toString();(!e||e.toString()!=g)&&f.p(nb(g))}}rb.call(this,a,b)}ga(Eb,rb);var Fb;a:{try{Fb=!!window.localStorage.getItem;break a}catch(Hb){}Fb=k}n=Eb.prototype;
n.K=function(){this.D=x();if(W(this)){for(var a=Y(this.b,"log"),b=100>=a.scrollHeight-(a.scrollTop+a.offsetHeight),c=0;c<this.j.length;c++){var d=this.b.h("div","logmsg");d.innerHTML=this.j[c];a.appendChild(d)}this.j.length=0;this.X();b&&(a.scrollTop=a.scrollHeight)}};
n.L=function(){if(W(this)){var a=this.a.document;a.open();a.write('<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>Logging: '+this.f+"</title><style>"+this.t()+'</style></head><body><div id="log" style="overflow:auto"></div><div id="head"><p><b>Logging: '+this.f+"</b></p><p>"+this.$+'</p><span id="clearbutton">clear</span><span id="exitbutton">exit</span><span id="openbutton">options</span></div><div id="options"><big><b>Options:</b></big><div id="optionsarea"></div><span id="closebutton">save and close</span></div></body></html>');
a.close();(A?a.body:this.a).onresize=w(this.X,this);this.b=new X(a);Y(this.b,"openbutton").onclick=w(this.la,this);Y(this.b,"closebutton").onclick=w(this.ca,this);Y(this.b,"clearbutton").onclick=w(this.ba,this);Y(this.b,"exitbutton").onclick=w(this.ga,this);yb(this)}};
n.la=function(){var a=Y(this.b,"optionsarea");a.innerHTML="";for(var b=Ib(),c=this.b,d=0;d<b.length;d++){var f=V(b[d]),f=c.h("div",{},Jb(this,"sel"+b[d],f.c?f.c.name:"INHERIT"),c.h("span",{},b[d]||"(root)"));a.appendChild(f)}Y(this.b,"options").style.display="block";return k};
function Jb(a,b,c){for(var a=a.b,b=a.h("select",{id:b}),d=0;d<mb.length;d++){var f=mb[d],e=a.h("option",{},f.name);c==f.name&&(e.selected=i);b.appendChild(e)}b.appendChild(a.h("option",{selected:"INHERIT"==c},"INHERIT"));return b}
n.ca=function(){Y(this.b,"options").style.display="none";for(var a=Ib(),b=this.b,c=0;c<a.length;c++){var d=V(a[c]),f=Y(b,"sel"+a[c]),f=f.options[f.selectedIndex].text;"INHERIT"==f?d.p(j):d.p(nb(f))}if(Fb){a=Ib();b=Gb();for(c=0;c<a.length;c++)d="fancywindow.sel."+a[c],f=V(a[c]).c,d in b?f?window.localStorage.getItem(d)!=f.name&&window.localStorage.setItem(d,f.name):window.localStorage.removeItem(d):f&&window.localStorage.setItem(d,f.name)}return k};
n.X=function(){var a=this.b,b=Y(a,"log"),c=Y(a,"head");b.style.top=c.offsetHeight+"px";b.style.height=a.l.body.offsetHeight-c.offsetHeight-(A?4:0)+"px"};n.ga=function(){vb(this,k);this.a&&this.a.close()};n.t=function(){return Eb.I.t.call(this)+"html,body{height:100%;width:100%;margin:0px;padding:0px;background-color:#FFF;overflow:hidden}*{}.logmsg{border-bottom:1px solid #CCC;padding:2px;font:90% monospace}#head{position:absolute;width:100%;font:x-small arial;border-bottom:2px solid #999;background-color:#EEE;}#head p{margin:0px 5px;}#log{position:absolute;width:100%;background-color:#FFF;}#options{position:absolute;right:0px;width:50%;height:100%;border-left:1px solid #999;background-color:#DDD;display:none;padding-left: 5px;font:normal small arial;overflow:auto;}#openbutton,#closebutton{text-decoration:underline;color:#00F;cursor:pointer;position:absolute;top:0px;right:5px;font:x-small arial;}#clearbutton{text-decoration:underline;color:#00F;cursor:pointer;position:absolute;top:0px;right:80px;font:x-small arial;}#exitbutton{text-decoration:underline;color:#00F;cursor:pointer;position:absolute;top:0px;right:50px;font:x-small arial;}select{font:x-small arial;margin-right:10px;}hr{border:0;height:5px;background-color:#8c8;color:#8c8;}"};
function Gb(){for(var a={},b=0,c=window.localStorage.length;b<c;b++){var d=window.localStorage.key(b);d!=j&&0==d.lastIndexOf("fancywindow.sel.",0)&&(a[d]=i)}return a}function Ib(){var a=[],b=0,c;for(c in pb)a[b++]=c;a.sort();return a};var Kb=1;document.getElementById("world").innerHTML="world";var Lb="now this--addThis",Lb=" :: "+(Lb+"addThis");document.getElementById("output").innerHTML="100 -- "+Lb;
Sa(document.getElementById("openFancyWindow"),"click",function(a){a.preventDefault();a=new Eb("main");vb(a,i);a.i();var a=":: #"+Kb++,b=V("example.sample2.launchFancyWindow");b.log(lb,"Hello World! This is a config level logging type "+a,h);b.info("This is an info level logging type "+a);b.log(jb,"This is a warning level logging type "+a,h);b.log(ib,"A severe level logging type "+a,h);b.log(hb,"A shout level logging type "+a,h)});function Mb(){console.log("FALSE")}var Nb=["example","deb"],Z=q;
!(Nb[0]in Z)&&Z.execScript&&Z.execScript("var "+Nb[0]);for(var Ob;Nb.length&&(Ob=Nb.shift());){var Pb;if(Pb=!Nb.length)Pb=Mb!==h;Pb?Z[Ob]=Mb:Z=Z[Ob]?Z[Ob]:Z[Ob]={}};}).call(this);
